apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master-job
spec:
  template:
    spec:
      containers:
      - name: jmeter-master
        image: macpellow/jmeter-master:latest
        command: ["/run-distributed-test.sh"]
      restartPolicy: Never